name: smartcook
description: "A new Flutter project."

publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: ^3.5.0


dependencies:
  flutter:
    sdk: flutter

 
  cupertino_icons: ^1.0.8
  google_sign_in: ^6.2.2
  firebase_core: ^3.11.0
  firebase_auth: ^5.5.0
  smooth_page_indicator: ^2.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  
  flutter_lints: ^6.0.0


flutter:

  
  uses-material-design: true

  assets:
    - image/mainLogo.jpg
    - image/starLogo.png
    - image/google.png
    - image/apple.png
    - image/password.png
    - image/mail.png
    - image/gembok.png
    - image/suksesImage.png
    - image/ob1.png
    - image/ob2.png
    - image/ob3.png
    - image/urutan1.png
    - image/urutan2.png
    - image/urutan3.png
    - image/personalInformation.png
    - image/jenisKelaminCowo.png
    - image/jenisKelaminCewe.png
    - image/style1.png
    - image/style2.png
    - image/style3.png
    - image/style4.png 
    - image/style5.png
    - image/style6.png
    - image/style7.png
    - image/style8.png
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #

